sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - build
branches:
  only:
  - master
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
